pip install altgraph
pip install certifi
pip install charset-normalizer
pip install customtkinter
pip install darkdetect
pip install idna
pip install monkey
pip install MouseInfo
pip install packaging
pip install pefile
pip install PyAutoGUI
pip install PyGetWindow
pip install pyinstaller
pip install pyinstaller-hooks-contrib
pip install PyMsgBox
pip install pyperclip
pip install PyRect
pip install PyScreeze
pip install pytweening
pip install pywin32
pip install pywin32-ctypes
pip install requests
pip install rotate-screen
pip install setuptools
pip install urllib3